### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by sanom** [ebu/mcma-projects#2]
The code in develop branch does not start a workflow. It might be caused by the following, no?

https://github.com/ebu/mcma-projects/blob/develop/multi-cloud-ai-workflow/website/src/app/services/workflow.service.ts

Line 19-21  ResourceManager has only one argument. There must be more one, i.e. token, no ?

**Comment by evanverneyfink** [comment]
Changes for authentication have not been made for the UI yet. I'm hoping to have these changes, as well as a number of others related to authentication, committed this morning.

**Comment by joostrovers** [comment]
This problem has been solved
