### ISSUE TITLE
Website config.json

### ISSUE THREAD

**Issue by eyalerez1** [ebu/mcma-projects#3]
Hi,

Thanks for the very cool project.

I've deployed the project using Terraform successfully and now I want to run the demo website.
When I run "ng serve" and open the browser I get the error for missing "config.json" file.

I created the file and tried to fill it but had no success...
Can you please publish an example config.json file?

Thanks.

**Comment by eyalerez1** [comment]
Nevermind, I've found the terraform.output file

**Comment by joostrovers** [comment]
Thank you for trying out the project and I'm glad you figured out your issue by yourself. However, since you had this confusion in the first place, it means we should improve our documentation a bit. Please let us know if you encounter any other issue.
